[project]
name = "lance-playground"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "av>=18.1.0",
    "numpy>=2.4.6",
    "pillow>=12.3.0",
    "pylance>=10.0.0",
    "streamlit>=1.61.1",
]

[project.scripts]
lance-playground = "lance_playground:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
